name: CI сборка для проекта

on:
  push:
    branches:
      - 'master'
      - 'i[0-9]+-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Получить код
        uses: actions/checkout@v4

      - name: Установить Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Установаить Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.13'

      - name: Проверка версии Gradle
        run: gradle --version

      - name: Установка Gradle wrapper
        run: gradle wrapper --gradle-version=8.13

      - name:  Предоставление прав для gradlew
        run: chmod +x gradlew

      - name: Запустить тесты
        run: ./gradlew test
